In [1]:
import numpy as np


In [119]:
D, N = 5, 10000
noise_weight = 10
noise = np.random.normal(loc=0, scale=1, size=N)

In [122]:
a = np.random.randint(low = 1, high = 20, size=D)
X = np.array([np.random.normal(loc=0, scale=1, size=N) for _ in range(D)]).transpose()
y = np.random.normal(loc=0, scale=1, size=N)

In [132]:
Cov    = np.matmul(X.T, X) / N
invCov = np.linalg.inv(Cov)
a = np.matmul(np.matmul(invCov, X.T),y)

In [133]:
a

array([-105.49126458, -192.92530937,   20.99149425,  -40.5455246 ,
       -149.4766284 ])

In [139]:
S  = y - np.matmul(X, a)
S2 = np.matmul(S.T, S) / np.matmul(y.T, y)

S

array([ 168.8651776 , -157.33772522,  447.93381423, ..., -176.85308171,
       -339.91472207, -303.8984753 ])

In [153]:
a = np.array(a, size=(5,1))

TypeError: array() got an unexpected keyword argument 'size'

In [113]:
r  = np.matmul(X.T, y)
invCov = np.linalg.inv(Cov)
ap = np.matmul(invCov, r) /N


In [114]:
ap


array([6.13479722, 5.39586888, 5.08664011, 0.85018929, 9.65818887])

In [120]:
z = np.random.normal(loc=0, scale=1, size=N)

In [121]:
np.matmul(z.T, z) / N

1.0072977979298212